### ISSUE TITLE
API Extension azure_authentication & subscription access_key are always being considered as modified

### ISSUE THREAD

**Issue by sudeep1607** [labd/terraform-provider-commercetools#306]
Terraform version:  1.1.4
Provider version: 1.4.2
Resource: commercetools_api_extension & commercetools_subscription

On every terraform apply, 
 1) The API Extensions are getting updated since azure_authentication is changed (but it is not)
 2) The subscription is getting modified since access_key is changed (but it is not)

```
  ~ resource "commercetools_api_extension" "api_extension" {
        id            = "ex-uuid"
        # (3 unchanged attributes hidden)
      ~ destination {
          ~ azure_authentication = (sensitive)
            # (6 unchanged attributes hidden)
        }
        # (1 unchanged block hidden)
    }

  ~ resource "commercetools_subscription" "subscription" {
        id      = "ex-uuid"
        # (2 unchanged attributes hidden)
      ~ destination {
          ~ access_key        = (sensitive value)
            # (10 unchanged attributes hidden)
        }
        # (5 unchanged blocks hidden)
    }
```

This looks to be similar to issue mentioned at https://github.com/labd/terraform-provider-commercetools/issues/284

**Comment by mvantellingen** [comment]
Should be fixed in 1.4.3

**Comment by sudeep1607** [comment]
@mvantellingen  We are still seeing the same behavior for commercetools_api_extension resource even after upgrading to 1.4.3 version. commercetools_subscription looks good after the fix
