### ISSUE TITLE
terraform plan/apply failing using credentials stored as environment variables

### ISSUE THREAD

**Issue by dmi-clopez** [labd/terraform-provider-commercetools#338]
**Information**
Terraform version: 
Terraform v1.3.7
on darwin_arm64
\+ provider registry.terraform.io/labd/commercetools v1.6.3
Resource:
All Commercetools resources
**To Reproduce**
When configuring the Commercetools provider exclusively using environment variables, we get the following error:

```hcl
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/labd/commercetools" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: Plugin error
│
│   with provider["registry.terraform.io/labd/commercetools"],
│   on <empty> line 0:
│   (source code not available)
│
│ The plugin returned an unexpected error from plugin.(*GRPCProvider).ValidateProviderConfig: rpc error: code = Unknown desc = got different PrepareProviderConfig PreparedConfig response from multiple servers, not sure which to use
```

This only happens when you run the provider with environment variables. If you configure the credentials explicitly, it works, like this.

```hcl
provider "commercetools" {
  client_id     = "xxxxxxxxxxxxxxxxxxx"
  client_secret = "yyyyyyyyyyyyyyyyyyyyyyyy"
  project_key   = "demo"
  scopes        = "manage_project:demo manage_api_clients:demo view_api_clients:demo view_audit_log:demo"
  api_url       = "https://api.us-central1.gcp.commercetools.com"
  token_url     = "https://auth.us-central1.gcp.commercetools.com"
}

```

Running Terraform with `TF_LOG=TRACE` outputs [the following](https://gist.github.com/dmi-clopez/f8130a15ef8b7c3658924b6ed5e824f3)

**Comment by mvantellingen** [comment]
I think we fixed this with https://github.com/labd/terraform-provider-commercetools/pull/336/commits/d358a34bfda6085523b15cd01b69f3cb69ff23d2 

Will merge the PR today and do a release

**Comment by jahernandezmartinez13** [comment]
We tested the new version v1.6.4 and the error is still appearing:

```
2023-01-24T11:48:37.366+0100 [ERROR] provider.terraform-provider-commercetools_v1.6.4: Error from downstream: tf_req_id=4f76081a-cbf1-36ce-6b3a-8cdbaa2e90f4 error="got different PrepareProviderConfig PreparedConfig response from multiple servers, not sure which to use" tf_proto_version=5.3 tf_provider_addr=registry.terraform.io/labd/commercetools tf_rpc=PrepareProviderConfig @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:529 @module=sdk.proto timestamp=2023-01-24T11:48:37.366+0100
2023-01-24T11:48:37.366+0100 [ERROR] plugin.(*GRPCProvider).ValidateProviderConfig: error="rpc error: code = Unknown desc = got different PrepareProviderConfig PreparedConfig response from multiple servers, not sure which to use"
2023-01-24T11:48:37.367+0100 [ERROR] vertex "provider[\"registry.terraform.io/labd/commercetools\"]" error: Plugin error
data.terraform_remote_state.ct_acc_terraform_gcp_dev: Read complete after 1s
2023-01-24T11:48:38.028+0100 [INFO]  backend/local: plan operation completed
╷
│ Error: Plugin error
│ 
│   with provider["registry.terraform.io/labd/commercetools"],
│   on provider.tf line 1, in provider "commercetools":
│    1: provider "commercetools" {
│ 
│ The plugin returned an unexpected error from plugin.(*GRPCProvider).ValidateProviderConfig: rpc error: code = Unknown desc = got different
│ PrepareProviderConfig PreparedConfig response from multiple servers, not sure which to use
╵
```

If we add the variables to the provider config (not in environment variables), it works
